### ISSUE TITLE
Understanding rotate_uv

### ISSUE THREAD

**Issue by anthony-meza** [ggebbie/ECCOtour.jl#54]
The rotate_uv function is not identical to the UVtoUEVN in MeshArrays.jl. However, rotate_uv obeys conservation of volume better than UVtoUEVN. One main difference is that UVtoUEVN interpolates the velocities to the grid center before rotating. Whether or not this a necessary step is still in question.

**Comment by ggebbie** [comment]
`rotate_velocity!`:  it does center the velocity then rotate it.

https://github.com/ggebbie/ECCOtour.jl/blob/main/src/ECCOtour.jl#L1780

But does it conserve volume accurately enough for @anthony-meza ?

**Comment by ggebbie** [comment]
Hope this one is good enough to close. Please re-open if there is a lingering issue.
